### ISSUE TITLE
Project infinitive build time

### ISSUE THREAD

**Issue by Kemsekov** [jmacato/Synfonia#19]
I cannot build project. When i try to run it everyting i get is constant loading screen.
[https://drive.google.com/file/d/1AWoS5r12Rj55Pjq4CELr6-3FsgUnGBi5/view?usp=sharing](url)

**Comment by jmacato** [comment]
@Kemsekov i can't access the google drive link you sent but can you post screenshots directly here instead?

**Comment by PathogenDavid** [comment]
@Kemsekov Package restore takes a very long time on this project and Visual Studio doesn't give much feedback during package restore.

If you build with `dotnet build --verbosity normal` or turn up the build verbosity in Visual Studio you will see the individual NuGet API requests going by if you want some confidence it's actually doing something.
