### ISSUE TITLE
Can't initiate playing music after music was already played

### ISSUE THREAD

**Issue by PathogenDavid** [jmacato/Synfonia#20]
Version used: a74e6f7b799d8240edf672b590027264095fc91a

Running on Windows 10 2004

# Steps to reproduce

1. Start playing some sweet tunes
2. Double-click another album to switch to that one
3. Right-click another album and select play

# Expected behavior

After both 2 and 3 the different albums start playing

# Actual behavior

Nothing happens

**Comment by jmacato** [comment]
the default behavior is that when you play another album, it adds it to the back of the queue... we could correct that later when me & @danwalmsley gets some spare time in fixing things around here :)

**Comment by jmacato** [comment]
@PathogenDavid yeah, the UX here needs some more polishing but there's only 24hrs in a day haha.. i wish i can fix things here asap but we're just swamped right now :'(

**Comment by PathogenDavid** [comment]
Yup, no worries, I know the feeling!
